---
title: "Extra Object Project Experiment"
author: "Sarah"
date: "27/07/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load in Data

```{r load packages}

rm(list = ls()) #run this line to clear your environment
library(lme4); library(lmerTest); library(tidyverse); library(data.table); library(dtplyr); library(effsize); library(pwr)

data_dir = "~/Desktop/ObjectProject/extra experiment/data/"



```

```{r load data and save CSV filename to a new column}
relevantData = list.files(path = data_dir, full.names = TRUE)

data = data.table()
for (i in relevantData) {
  df_temp = setDT(read.csv(i))
  df_temp[, filename := i]
  data = rbind(data, df_temp)
}

data = setDT(data)

```

```{r new columns to denote condition and batch}

data$group = NULL #remove group col

#identify batches 
data[grep(pattern = "extraexperiment_1_", x = filename, ), batch := 1 ]
data[grep(pattern = "extraexperiment_2_", x = filename, ), batch := 2 ]
data[grep(pattern = "extraexperiment_3_", x = filename, ), batch := 3 ]
data[grep(pattern = "extraexperiment_4_", x = filename, ), batch := 4 ]
data[grep(pattern = "extraexperiment_5_", x = filename, ), batch := 5 ]
data[grep(pattern = "extraexperiment_6_", x = filename, ), batch := 6 ]
data[grep(pattern = "extraexperiment_7_", x = filename, ), batch := 7 ]
data[grep(pattern = "extraexperiment_8_", x = filename, ), batch := 8 ]
data[grep(pattern = "extraexperiment_9_", x = filename, ), batch := 9 ]
data[grep(pattern = "extraexperiment_10_", x = filename, ), batch := 10 ]
data[grep(pattern = "extraexperiment_11_", x = filename, ), batch := 11 ]
data[grep(pattern = "extraexperiment_12_", x = filename, ), batch := 12 ]
data[grep(pattern = "extraexperiment_13_", x = filename, ), batch := 13 ]
data[grep(pattern = "extraexperiment_14_", x = filename, ), batch := 14 ]
data[grep(pattern = "extraexperiment_15_", x = filename, ), batch := 15 ]
data[grep(pattern = "extraexperiment_16_", x = filename, ), batch := 16 ]

to_assign_ids = data[, .N, keyby = .(subject, batch)] 
to_assign_ids[, participant := 1:.N] #add new participant column
to_assign_ids$N = NULL

data = left_join(data, to_assign_ids)

data = data %>% arrange(participant) %>% select(participant, everything()) # arrange by participant

# remove unnecessary columns

data$filename = NULL

# rename key presses for retrieval phase to be interpretable
data[blockcode == "retrieval" & response == "36", response := "old"]
data[blockcode == "retrieval" & response == "37", response := "new"]


```

Maybe remove participants who were bad with data cleaning

# analyse retrieval

```{r view RT latency distribution}

hist(data[blockcode == "retrieval" & latency < 3000]$latency, breaks = 50) #cutoff around 300ms

HR_by_condition = data[latency %between% c(300,1999) & blockcode == "retrieval", .(mean = mean(correct)), by = .(old_object_condition)]

```

```{r try removing participants I said were bad}

#data_clean = data[!batch %in% c(1,7)]
#view(data_clean[batch == 3 & subject %in% c(5,15)]) #participant 6 and 16
#view(data_clean[batch == 8 & subject %in% c(4,8)]) # participant 5 and 10
#data_clean = data_clean[!participant %in% c(5,6,10,16)]

#HR_by_condition_clean = data_clean[latency %between% c(300,1999) & blockcode == "retrieval", .(mean = mean(correct)), by = .(old_object_condition, participant)]
#unique(HR_by_condition_clean$participant)

```

# data cleaning 
```{r remove abnormal trial latencies}

retrieval = data[blockcode == "retrieval" & latency %between% c(300,1999)]

exclude_incomplete_retrieval = retrieval[, .N, by = .(participant)][N < 160]$participant #more than half their trials were of abnormal latency or they didn't finish

retrieval = retrieval[!participant %in% c(exclude_incomplete_retrieval)]

```

# calculate effect size
```{r effect size}

random = retrieval[batch %in% c(1:8)]
software = retrieval[batch %in% c(9:16)]

unique(random$participant) #38
unique(software$participant) #40

cohen.d(random[old_object_condition == 1]$correct, random[old_object_condition == 3]$correct)

cohen.d(software[old_object_condition == 1]$correct, software[old_object_condition == 3]$correct)

```


# power analysis

```{r power analysis}

# power analysis for random
pwr.t.test(d = .437, sig.level = .05, power = .8, type = ("paired"))
# n is 43


# power analysis for software
pwr.t.test(d = .525, sig.level = .05, power = .8, type = ("paired"))
# n is 30

#this means using the software results in 30% less participants needed to achieve the same power
#(43-30)/43

```

# analyse what happens when only a few stimuli are used (10 per condition)

```{r segment out first 10 stimuli}

snip_9_10 = c("A0.jpg","A1.jpg","A2.jpg","A3.jpg","A4.jpg","A5.jpg","A6.jpg","A7.jpg","A8.jpg","A9.jpg","B0.jpg","B1.jpg","B2.jpg","B3.jpg","B4.jpg","B5.jpg","B6.jpg","B7.jpg","B8.jpg","B9.jpg")
snip_11_12 = c("C0.jpg","C1.jpg","C2.jpg","C3.jpg","C4.jpg","C5.jpg","C6.jpg","C7.jpg","C8.jpg","C9.jpg","D0.jpg","D1.jpg","D2.jpg","D3.jpg","D4.jpg","D5.jpg","D6.jpg","D7.jpg","D8.jpg","D9.jpg")
snip_13_14 = c("E0.jpg","E1.jpg","E2.jpg","E3.jpg","E4.jpg","E5.jpg","E6.jpg","E7.jpg","E8.jpg","E9.jpg","F0.jpg","F1.jpg","F2.jpg","F3.jpg","F4.jpg","F5.jpg","F6.jpg","F7.jpg","F8.jpg","F9.jpg")
snip_15_16 = c("G0.jpg","G1.jpg","G2.jpg","G3.jpg","G4.jpg","G5.jpg","G6.jpg","G7.jpg","G8.jpg","G9.jpg","H0.jpg","H1.jpg","H2.jpg","H3.jpg","H4.jpg","H5.jpg","H6.jpg","H7.jpg","H8.jpg","H9.jpg")


software_snippet = software[
  (batch %in% c(9,10) & stimulus %in% snip_9_10) | 
    (batch %in% c(11,12) & stimulus %in% snip_11_12) |
    (batch %in% c(13,14) & stimulus %in% snip_13_14) |
    (batch %in% c(15,16) & stimulus %in% snip_15_16)]

snip_1_2 = c("Blanket.jpg", "Candy_Chocolate.jpg", "Cake_Wedding.jpg", "Helmet_Construction.jpg","SculptureMetalFish.jpg", "Notebook.jpg", "GasBurner.jpg", "Guitar_Acoustic.jpg", "Toy_BlocksPlastic Colourful.jpg", "TinChristmas.jpg", "Tickets_Blank.jpg",
"Desk_School.jpg", "LeatherPuncherTool.jpg", "Toy_StackingRing.jpg", "Drink_Green.jpg", "Bullet.jpg", "Ashtray_Empty.jpg", "NeedlesAcupuncture.jpg","Beater_Electric.jpg", "Generator.jpg")
snip_3_4 = c("TurkeyDinner.jpg", "Broom_Long.jpg", "Ball_8.jpg", "SkullDeer.jpg", "Shield_Antique.jpg",
"Pajamas.jpg", "Radio_Vintage.jpg","BicycleGear.jpg","Ball_Disco.jpg","Pig.jpg","CookieCutter_Tree.jpg", "Tire_Hollow.jpg", "Lamp_TableWhite.jpg", "LampPost_OneBulb.jpg", "Glass_Martini.jpg","Currants.jpg","SkiPoles.jpg", "CrepeMaker.jpg", "Switch_LightWhite.jpg","Paddle_Beach.jpg")
snip_5_6 = c("Makeup_Compact.jpg", "Ladybug.jpg", "Corkboard.jpg", "Hedgehog.jpg", "Walker_Blue.jpg", "Nuts_Pecan.jpg", "Branch.jpg", "Cannon.jpg", "ManholeCover.jpg","Bowl_Glass.jpg","CoffeeLid.jpg", "Heelpad.jpg","Can_Oblong.jpg","Briefcase_Silver.jpg","Glass_Beer.jpg","Carousel.jpg","Case_Pencil.jpg","TailLight.jpg","IceCream_Popsicle.jpg","Earring_Hoop.jpg")
snip_7_8 = c("WaterCooler.jpg","Ostrich.jpg","ShoeLace_Flat.jpg","Blueberry.jpg","Sphinx.jpg", "Bucket_WoodenLight.jpg","WaterHeater.jpg","Walkman.jpg","Toy_DonkeyFur.jpg","Case_CD.jpg","FuzzyDice.jpg","Bagpipes.jpg","GrillRack.jpg","Stick_IceHockey.jpg","Lips_Wax.jpg","Dice.jpg","Snorkle.jpg","Glasses_Sun.jpg","Toy_Rooster.jpg","Suit_Women.jpg")

random_snippet = random[
  (batch %in% c(1,2) & stimulus %in% snip_1_2) | 
    (batch %in% c(3,4) & stimulus %in% snip_3_4) |
    (batch %in% c(5,6) & stimulus %in% snip_5_6) |
    (batch %in% c(7,8) & stimulus %in% snip_7_8)]

```


```{r segmented effect size}

cohen.d(random_snippet[old_object_condition == 1]$correct, random_snippet[old_object_condition == 3]$correct) #.569

cohen.d(software_snippet[old_object_condition == 1]$correct, software_snippet[old_object_condition == 3]$correct) #.69

```

```{r segmented power analysis}

# power analysis for random
pwr.t.test(d = .52, sig.level = .05, power = .8, type = ("paired"))
# n is 31


# power analysis for software
pwr.t.test(d = .7, sig.level = .05, power = .8, type = ("paired"))
# n is 18

#this means using the software results in 30% less participants needed to achieve the same power at smaller level of stimuli
#(26-18)/26

```

# loop through 10 randomly selected stimuli 

```{r loop through random stimuli}

#load condition files

list_1 <- read.csv("list_1.csv", header = FALSE)
list_2 <- read.csv("list_2.csv", header = FALSE)
list_3 <- read.csv("list_3.csv", header = FALSE)
list_4 <- read.csv("list_4.csv", header = FALSE)
list_5 <- read.csv("list_5.csv", header = FALSE)
list_6 <- read.csv("list_6.csv", header = FALSE)
list_7 <- read.csv("list_7.csv", header = FALSE)
list_8 <- read.csv("list_8.csv", header = FALSE)


#select 10 random stimuli for each of 

effect_sizes <- c()

n = 10

for (i in 1:100) {
  sample_1 = sample_n(list_1, n)
  sample_2 = sample_n(list_2, n)
  sample_3 = sample_n(list_3, n)
  sample_4 = sample_n(list_4, n)
  sample_5 = sample_n(list_5, n)
  sample_6 = sample_n(list_6, n)
  sample_7 = sample_n(list_7, n)
  sample_8 = sample_n(list_8, n)
  
  
  snippet = random[
  (batch %in% c(1,2) & stimulus %in% sample_1$V1 | stimulus %in% sample_2$V1) | 
    (batch %in% c(3,4) & stimulus %in% sample_3$V1 | stimulus %in% sample_4$V1) |
    (batch %in% c(5,6) & stimulus %in% sample_5$V1 | stimulus %in% sample_6$V1) |
    (batch %in% c(7,8) & stimulus %in% sample_7$V1 | stimulus %in% sample_8$V1)]
  
  ef = cohen.d(snippet[old_object_condition == 1]$correct, snippet[old_object_condition == 3]$correct)
  effect_sizes <- c(effect_sizes, ef$estimate)
}
return(effect_sizes)

effect_sizes

hist(effect_sizes)

```


# also calculate dprime and not just hit rate

```{r corrected HR}
#calculate corrected hit rate

random[, HR := mean(correct), by = participant]
random[, avg_mem := correct - HR, by = participant]

effect_sizes <- c()

n = 10

for (i in 1:100) {
  sample_1 = sample_n(list_1, n)
  sample_2 = sample_n(list_2, n)
  sample_3 = sample_n(list_3, n)
  sample_4 = sample_n(list_4, n)
  sample_5 = sample_n(list_5, n)
  sample_6 = sample_n(list_6, n)
  sample_7 = sample_n(list_7, n)
  sample_8 = sample_n(list_8, n)
  
  
  snippet = random[
  (batch %in% c(1,2) & stimulus %in% sample_1$V1 | stimulus %in% sample_2$V1) | 
    (batch %in% c(3,4) & stimulus %in% sample_3$V1 | stimulus %in% sample_4$V1) |
    (batch %in% c(5,6) & stimulus %in% sample_5$V1 | stimulus %in% sample_6$V1) |
    (batch %in% c(7,8) & stimulus %in% sample_7$V1 | stimulus %in% sample_8$V1)]
  
  ef = cohen.d(snippet[old_object_condition == 1]$avg_mem, snippet[old_object_condition == 3]$avg_mem)
  effect_sizes <- c(effect_sizes, ef$estimate)
}
return(effect_sizes)

mean(effect_sizes) .52

hist(effect_sizes) 



#do corrected HR with software

software[, HR := mean(correct), by = participant]
software[, avg_mem := correct - HR, by = participant]

software_snippet = software[
  (batch %in% c(9,10) & stimulus %in% snip_9_10) | 
    (batch %in% c(11,12) & stimulus %in% snip_11_12) |
    (batch %in% c(13,14) & stimulus %in% snip_13_14) |
    (batch %in% c(15,16) & stimulus %in% snip_15_16)]

cohen.d(software_snippet[old_object_condition == 1]$avg_mem, software_snippet[old_object_condition == 3]$avg_mem) #.70

```


#dprime

```{r }

```

